# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NMTrial' do

  pod 'Alamofire', '~> 3.1.2'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NMTrial

  target 'NMTrialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NMTrialUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
